name: uac-analyzer
services:

  uac-analyzer:
    image: mwdle/uac-analyzer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uac-analyzer
    restart: unless-stopped
    networks:
      - ollama
    # Keep the container running
    stdin_open: true

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    networks:
      - ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

volumes:
  ollama:
    name: ollama

networks:
  ollama: